# coding: utf-8

"""
    Libre:Match API

    stable, reliable and feature-rich API for match information, leaderboards, and tournament organisation for the Age of Empires multiplayer community

    The version of the OpenAPI document: 1.0.0
    Contact: info@librematch.org
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Libre:Match API",
    description="stable, reliable and feature-rich API for match information, leaderboards, and tournament organisation for the Age of Empires multiplayer community",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
