# coding: utf-8

"""
    Libre:Match API

    stable, reliable and feature-rich API for match information, leaderboards, and tournament organisation for the Age of Empires multiplayer community

    The version of the OpenAPI document: 1.0.0-DRAFT
    Contact: info@librematch.org
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.api_token_validation_api import router as APITokenValidationApiRouter
from openapi_server.apis.account_registration_api import router as AccountRegistrationApiRouter
from openapi_server.apis.administration_api import router as AdministrationApiRouter
from openapi_server.apis.adminstration_api import router as AdminstrationApiRouter
from openapi_server.apis.authentication_api import router as AuthenticationApiRouter
from openapi_server.apis.database_api import router as DatabaseApiRouter
from openapi_server.apis.definition_api import router as DefinitionApiRouter
from openapi_server.apis.information_api import router as InformationApiRouter
from openapi_server.apis.internal_api import router as InternalApiRouter
from openapi_server.apis.leaderboards_api import router as LeaderboardsApiRouter
from openapi_server.apis.match_data_api import router as MatchDataApiRouter
from openapi_server.apis.profile_administration_api import router as ProfileAdministrationApiRouter
from openapi_server.apis.statistics_api import router as StatisticsApiRouter
from openapi_server.apis.status_check_api import router as StatusCheckApiRouter
from openapi_server.apis.team_administration_api import router as TeamAdministrationApiRouter
from openapi_server.apis.teams_api import router as TeamsApiRouter
from openapi_server.apis.tournament_administration_api import router as TournamentAdministrationApiRouter
from openapi_server.apis.tournaments_api import router as TournamentsApiRouter
from openapi_server.apis.user_administration_api import router as UserAdministrationApiRouter
from openapi_server.apis.user_adminstration_api import router as UserAdminstrationApiRouter
from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Libre:Match API",
    description="stable, reliable and feature-rich API for match information, leaderboards, and tournament organisation for the Age of Empires multiplayer community",
    version="1.0.0-DRAFT",
)

app.include_router(APITokenValidationApiRouter)
app.include_router(AccountRegistrationApiRouter)
app.include_router(AdministrationApiRouter)
app.include_router(AdminstrationApiRouter)
app.include_router(AuthenticationApiRouter)
app.include_router(DatabaseApiRouter)
app.include_router(DefinitionApiRouter)
app.include_router(InformationApiRouter)
app.include_router(InternalApiRouter)
app.include_router(LeaderboardsApiRouter)
app.include_router(MatchDataApiRouter)
app.include_router(ProfileAdministrationApiRouter)
app.include_router(StatisticsApiRouter)
app.include_router(StatusCheckApiRouter)
app.include_router(TeamAdministrationApiRouter)
app.include_router(TeamsApiRouter)
app.include_router(TournamentAdministrationApiRouter)
app.include_router(TournamentsApiRouter)
app.include_router(UserAdministrationApiRouter)
app.include_router(UserAdminstrationApiRouter)
app.include_router(DefaultApiRouter)
