# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class AuthorizationHeader(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AuthorizationHeader - a model defined in OpenAPI

        authorization_header: The authorization_header of this AuthorizationHeader.
    """

    authorization_header: str = Field(alias="AuthorizationHeader")

    @validator("authorization_header")
    def authorization_header_max_length(cls, value):
        assert len(value) <= 33
        return value

AuthorizationHeader.update_forward_refs()
