# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class LanguageString(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LanguageString - a model defined in OpenAPI

        _self: The _self of this LanguageString.
    """

    _self: str = Field(alias="self")

    @validator("_self")
    def _self_min_length(cls, value):
        assert len(value) >= 2
        return value

    @validator("_self")
    def _self_max_length(cls, value):
        assert len(value) <= 5
        return value

    @validator("_self")
    def _self_pattern(cls, value):
        assert value is not None and re.match(r"^([a-z]{2}){1}(-[A-Z]{2}){0,1}$", value)
        return value

LanguageString.update_forward_refs()
