# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Md5(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Md5 - a model defined in OpenAPI

        checksum: The checksum of this Md5.
    """

    checksum: str = Field(alias="checksum")

    @validator("checksum")
    def checksum_max_length(cls, value):
        assert len(value) <= 33
        return value

    @validator("checksum")
    def checksum_pattern(cls, value):
        assert value is not None and re.match(r"^[a-fA-F0-9]{32}$", value)
        return value

Md5.update_forward_refs()
