# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Timeframe(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Timeframe - a model defined in OpenAPI

        timeframe: The timeframe of this Timeframe.
    """

    timeframe: str = Field(alias="timeframe")

    @validator("timeframe")
    def timeframe_max_length(cls, value):
        assert len(value) <= 15
        return value

    @validator("timeframe")
    def timeframe_pattern(cls, value):
        assert value is not None and re.match(r"^example-TODO$", value)
        return value

Timeframe.update_forward_refs()
