# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Timeframe(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Timeframe - a model defined in OpenAPI

        _self: The _self of this Timeframe.
    """

    _self: str = Field(alias="self")

    @validator("_self")
    def _self_max_length(cls, value):
        assert len(value) <= 15
        return value

    @validator("_self")
    def _self_pattern(cls, value):
        assert value is not None and re.match(r"^\d\d\d\d-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01]) (00|[0-9]|1[0-9]|2[0-3]):([0-9]|[0-5][0-9]):([0-9]|[0-5][0-9])$", value)
        return value

Timeframe.update_forward_refs()
