# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Ulid(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Ulid - a model defined in OpenAPI

        ulid: The ulid of this Ulid.
    """

    ulid: str = Field(alias="ulid")

    @validator("ulid")
    def ulid_max_length(cls, value):
        assert len(value) <= 26
        return value

    @validator("ulid")
    def ulid_pattern(cls, value):
        assert value is not None and re.match(r"^[0-7][0-9A-HJKMNP-TV-Z]{25}$", value)
        return value

Ulid.update_forward_refs()
