# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class WwwAuthenticate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    WwwAuthenticate - a model defined in OpenAPI

        www_authenticate: The www_authenticate of this WwwAuthenticate.
    """

    www_authenticate: str = Field(alias="WwwAuthenticate")

    @validator("www_authenticate")
    def www_authenticate_max_length(cls, value):
        assert len(value) <= 33
        return value

WwwAuthenticate.update_forward_refs()
